"""Ajustes para o meu próprio site, só o que eu necessito

Revision ID: fe954a188b69
Revises: c9ddd27f8f1c
Create Date: 2026-04-30 18:33:19.385652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe954a188b69'
down_revision = 'c9ddd27f8f1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contato', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(), nullable=True))
        batch_op.drop_column('mensagem')
        batch_op.drop_column('nome')
        batch_op.drop_column('assunto')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contato', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assunto', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('nome', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('mensagem', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('password')

    # ### end Alembic commands ###
